### ISSUE TITLE
Add Full screen Modal for news articles 

### ISSUE THREAD

**Issue by nikhil96widhani** [nikhil96widhani/CovidDjango#8]
[Ref style1 from demo](https://joaopereirawd.github.io/animatedModal.js/) 

Modal bar triggers from navbar icon and is animated, covers fullscreen

**Comment by mohitdevda2797** [comment]
A little more description please.

**Comment by nikhil96widhani** [comment]
This link has 3 examples. I am planning if we can use style 1 instead of our existing modal for news as this one covers full screen and looks great

**Comment by mohitdevda2797** [comment]
Yes, the first one is nice. I will be working on it.
